import UIKit
import AVFoundation
import AVKit
import UniformTypeIdentifiers

final class CameraViewController: UIViewController {
    private let environment: AppEnvironment; private let session = AVCaptureSession(); private let movieOutput = AVCaptureMovieFileOutput(); private let preview = AVCaptureVideoPreviewLayer(); private var recordURL: URL?
    private let recordButton = UIButton(type: .custom); private let status = UIBuilder.label("●  READY TO PROTECT", style: AppTypography.caption, color: AppColors.success); private let timerLabel = UIBuilder.label("", style: AppTypography.headline, color: .white)
    private var startedAt: Date?
    init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }
    required init?(coder: NSCoder) { fatalError("Camera is created programmatically") }
    override func viewDidLoad() { super.viewDidLoad(); title = "TrueCut"; view.backgroundColor = .black; setupUI(); requestCamera() }
    override func viewDidLayoutSubviews() { super.viewDidLayoutSubviews(); preview.frame = view.bounds }
    private func setupUI() {
        preview.videoGravity = .resizeAspectFill; view.layer.insertSublayer(preview, at: 0)
        let top = UIBuilder.label("RECORD A PROTECTED ORIGINAL", style: AppTypography.caption, color: .white); top.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(top); status.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(status); timerLabel.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(timerLabel)
        recordButton.translatesAutoresizingMaskIntoConstraints = false; recordButton.backgroundColor = .white; recordButton.layer.cornerRadius = 36; recordButton.layer.borderWidth = 7; recordButton.layer.borderColor = UIColor.white.withAlphaComponent(0.35).cgColor; recordButton.addTarget(self, action: #selector(toggleRecording), for: .touchUpInside); recordButton.accessibilityLabel = "Record protected video"; view.addSubview(recordButton)
        let info = UIBuilder.label("Original videos remain on this device", style: AppTypography.caption, color: UIColor.white.withAlphaComponent(0.8)); info.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(info)
        NSLayoutConstraint.activate([top.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.md), top.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), status.topAnchor.constraint(equalTo: top.bottomAnchor, constant: AppSpacing.xs), status.leadingAnchor.constraint(equalTo: top.leadingAnchor), timerLabel.topAnchor.constraint(equalTo: status.bottomAnchor, constant: AppSpacing.sm), timerLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor), recordButton.centerXAnchor.constraint(equalTo: view.centerXAnchor), recordButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -AppSpacing.lg), recordButton.widthAnchor.constraint(equalToConstant: 72), recordButton.heightAnchor.constraint(equalToConstant: 72), info.centerXAnchor.constraint(equalTo: view.centerXAnchor), info.bottomAnchor.constraint(equalTo: recordButton.topAnchor, constant: -AppSpacing.md)])
        let tap = UITapGestureRecognizer(target: self, action: #selector(focus(_:))); view.addGestureRecognizer(tap)
    }
    private func requestCamera() { switch AVCaptureDevice.authorizationStatus(for: .video) { case .authorized: configureSession(); case .notDetermined: AVCaptureDevice.requestAccess(for: .video) { [weak self] granted in DispatchQueue.main.async { if granted { self?.configureSession() } else { self?.showPermission() } } }; default: showPermission() } }
    private func configureSession() { DispatchQueue.global(qos: .userInitiated).async { [weak self] in guard let self else { return }; session.beginConfiguration(); session.sessionPreset = .high; defer { session.commitConfiguration(); session.startRunning(); DispatchQueue.main.async { self.preview.session = self.session } }; guard let camera = AVCaptureDevice.default(for: .video), let input = try? AVCaptureDeviceInput(device: camera), session.canAddInput(input), session.canAddOutput(movieOutput) else { return }; session.addInput(input); session.addOutput(movieOutput); if let connection = movieOutput.connection(with: .video), connection.isVideoOrientationSupported { connection.videoOrientation = .portrait } } }
    @objc private func toggleRecording() { if movieOutput.isRecording { movieOutput.stopRecording(); startedAt = nil; timerLabel.text = "" } else { guard session.isRunning else { return }; let url = FileManager.default.temporaryDirectory.appendingPathComponent("capture-\(UUID().uuidString).mov"); recordURL = url; movieOutput.startRecording(to: url, recordingDelegate: self); startedAt = Date(); status.text = "●  RECORDING"; status.textColor = AppColors.danger; UIImpactFeedbackGenerator(style: .heavy).impactOccurred() } }
    @objc private func focus(_ gesture: UITapGestureRecognizer) { let point = gesture.location(in: view); guard let device = (session.inputs.first as? AVCaptureDeviceInput)?.device, device.isFocusPointOfInterestSupported else { return }; let focus = preview.captureDevicePointConverted(fromLayerPoint: point); try? device.lockForConfiguration(); device.focusPointOfInterest = focus; device.focusMode = .autoFocus; device.unlockForConfiguration() }
    private func showPermission() { let alert = UIAlertController(title: "Camera Access Needed", message: "TrueCut needs camera access to record protected videos.", preferredStyle: .alert); alert.addAction(UIAlertAction(title: "Cancel", style: .cancel)); alert.addAction(UIAlertAction(title: "Open Settings", style: .default) { _ in UIApplication.shared.open(URL(string: UIApplication.openSettingsURLString)! ) }); present(alert, animated: true) }
    private func finalize(url: URL) { status.text = "●  PROTECTING ORIGINAL"; status.textColor = AppColors.warning; Task { let digest = try? await environment.digestService.sha256(of: url); let signing = try? await environment.signingService.prepareKey(); let fingerprint = try? await environment.signingService.publicKeyFingerprint(); let evidence = digest.map { CaptureEvidence(captureID: UUID().uuidString, digest: $0, createdAt: Date(), locationDisclosure: .off) }; var credentials: SealedAsset?; if let evidence { credentials = try? await awaitSeal(url, evidence) }; let protectedState: ProtectionStatus = (signing != nil && digest != nil && credentials != nil) ? .protected : .incomplete; let finalURL = persistAsset(credentials?.url ?? url, captureID: evidence?.captureID ?? UUID().uuidString); let size = (try? FileManager.default.attributesOfItem(atPath: finalURL.path)[.size] as? NSNumber)?.int64Value ?? 0; let record = ProofRecord(id: UUID(), captureId: evidence?.captureID ?? UUID().uuidString, localAssetURL: finalURL, createdAt: Date(), duration: 0, width: 0, height: 0, frameRate: 0, locationDisclosure: .off, protectionStatus: protectedState, provenanceStatus: credentials == nil ? .incomplete : .verifiedOriginal, publicKeyFingerprint: fingerprint, digestHex: digest?.sha256Hex, fileSize: size); if finalURL != url { try? FileManager.default.removeItem(at: url) }; try? await environment.proofRepository.save(record); await MainActor.run { self.status.text = protectedState == .protected ? "●  PROTECTED ORIGINAL" : "●  PROTECTION INCOMPLETE"; self.status.textColor = protectedState == .protected ? AppColors.success : AppColors.warning; self.showResult(record) } } }
    private func awaitSeal(_ url: URL, _ evidence: CaptureEvidence) async throws -> SealedAsset { try await environment.credentialsService.seal(assetURL: url, evidence: evidence) }
    private func persistAsset(_ source: URL, captureID: String) -> URL { let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent("TrueCut/Originals", isDirectory: true); try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true); let destination = directory.appendingPathComponent("\(captureID).mov"); try? FileManager.default.removeItem(at: destination); do { try FileManager.default.moveItem(at: source, to: destination) } catch { try? FileManager.default.copyItem(at: source, to: destination) }; try? FileManager.default.setAttributes([.protectionKey: FileProtectionType.completeUnlessOpen], ofItemAtPath: destination.path); return destination }
    private func showResult(_ record: ProofRecord) { let title = record.protectionStatus == .protected ? "Protected Original" : "Protection incomplete"; let message = record.protectionStatus == .protected ? "Integrity evidence was created and saved locally." : "Your recording was saved, but Content Credentials could not be completed in this build."; let alert = UIAlertController(title: title, message: message, preferredStyle: .alert); alert.addAction(UIAlertAction(title: "Done", style: .default)); present(alert, animated: true) }
}
extension CameraViewController: AVCaptureFileOutputRecordingDelegate { func fileOutput(_ output: AVCaptureFileOutput, didFinishRecordingTo outputFileURL: URL, from connections: [AVCaptureConnection], error: Error?) { DispatchQueue.main.async { self.status.text = "●  READY TO PROTECT"; self.status.textColor = AppColors.success; if error == nil { self.finalize(url: outputFileURL) } } } }

final class ProofVaultViewController: UIViewController {
    let environment: AppEnvironment; let stack = UIStackView(); var records = [ProofRecord]()
    init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() { super.viewDidLoad(); title = "Proof Vault"; view.backgroundColor = AppColors.background; stack.axis = .vertical; stack.spacing = AppSpacing.md; stack.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(stack); NSLayoutConstraint.activate([stack.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.lg), stack.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), stack.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md)]); load() }
    private func load() { Task { records = (try? await environment.proofRepository.load()) ?? []; await MainActor.run { self.render() } } }
    private func render() { stack.arrangedSubviews.forEach { $0.removeFromSuperview() }; guard !records.isEmpty else { let empty = UIBuilder.label("No Protected Videos Yet\n\nVideos recorded with TrueCut will appear here.", style: AppTypography.title); empty.textAlignment = .center; stack.addArrangedSubview(empty); return }; for record in records { let b = UIBuilder.button("\(record.protectionStatus.title)   ·   \(record.createdAt.formatted(date: .abbreviated, time: .shortened))", image: record.protectionStatus == .protected ? AppIcons.shield : UIImage(systemName: "exclamationmark.shield"), primary: false); b.contentHorizontalAlignment = .left; b.addAction(UIAction { [weak self] _ in self?.navigationController?.pushViewController(ProofDetailViewController(record: record, environment: self!.environment), animated: true) }, for: .touchUpInside); stack.addArrangedSubview(b) } }
}
