import UIKit
import AVFoundation
import AVKit
import UniformTypeIdentifiers
import LocalAuthentication

final class CameraViewController: UIViewController {
    private let environment: AppEnvironment
    private let session = AVCaptureSession()
    private let movieOutput = AVCaptureMovieFileOutput()
    private let photoOutput = AVCapturePhotoOutput()
    private let preview = AVCaptureVideoPreviewLayer()
    private let recordButton = UIButton(type: .custom)
    private let status = UIBuilder.label("●  READY TO PROTECT", style: AppTypography.caption, color: AppColors.success)
    private let timerLabel = UIBuilder.label("", style: AppTypography.headline, color: .white)
    private let lensStack = UIStackView()
    private let modeControl = UISegmentedControl(items: ["Photo", "Video"])
    private let gridView = GridOverlayView()
    private var timer: Timer?
    private var recordingStartedAt: Date?
    private var isFinalizing = false
    private var selectedPosition: AVCaptureDevice.Position = .back
    private var locationDisclosure: LocationDisclosure = .off
    init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }
    required init?(coder: NSCoder) { fatalError("Camera is created programmatically") }
    override func viewDidLoad() { super.viewDidLoad(); title = "TrueCut"; view.backgroundColor = .black; setupUI(); requestCamera() }
    override func viewDidLayoutSubviews() { super.viewDidLayoutSubviews(); preview.frame = view.bounds; gridView.frame = view.bounds }
    private func setupUI() {
        preview.videoGravity = .resizeAspectFill; view.layer.insertSublayer(preview, at: 0); gridView.isHidden = true; view.addSubview(gridView)
        let top = UIBuilder.label("RECORD A PROTECTED ORIGINAL", style: AppTypography.caption, color: .white); top.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(top); status.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(status); timerLabel.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(timerLabel)
        let flip = UIButton(type: .system); flip.setImage(UIImage(systemName: "arrow.triangle.2.circlepath.camera"), for: .normal); flip.tintColor = .white; flip.addTarget(self, action: #selector(flipCamera), for: .touchUpInside); flip.accessibilityLabel = "Switch camera"; flip.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(flip)
        let grid = UIButton(type: .system); grid.setImage(UIImage(systemName: "grid"), for: .normal); grid.tintColor = .white; grid.addTarget(self, action: #selector(toggleGrid), for: .touchUpInside); grid.accessibilityLabel = "Toggle rule of thirds grid"; grid.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(grid)
        modeControl.selectedSegmentIndex = 1; modeControl.translatesAutoresizingMaskIntoConstraints = false; modeControl.addTarget(self, action: #selector(modeChanged), for: .valueChanged); modeControl.accessibilityLabel = "Capture mode"; view.addSubview(modeControl)
        lensStack.axis = .horizontal; lensStack.spacing = AppSpacing.xs; lensStack.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(lensStack)
        recordButton.translatesAutoresizingMaskIntoConstraints = false; recordButton.backgroundColor = .white; recordButton.layer.cornerRadius = 36; recordButton.layer.borderWidth = 7; recordButton.layer.borderColor = UIColor.white.withAlphaComponent(0.35).cgColor; recordButton.setImage(UIImage(systemName: "circle.fill"), for: .normal); recordButton.tintColor = .systemRed; recordButton.addTarget(self, action: #selector(toggleRecording), for: .touchUpInside); recordButton.accessibilityLabel = "Record protected video"; view.addSubview(recordButton)
        let info = UIBuilder.label("Original videos remain on this device", style: AppTypography.caption, color: UIColor.white.withAlphaComponent(0.8)); info.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(info)
        NSLayoutConstraint.activate([top.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.md), top.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), status.topAnchor.constraint(equalTo: top.bottomAnchor, constant: AppSpacing.xs), status.leadingAnchor.constraint(equalTo: top.leadingAnchor), timerLabel.topAnchor.constraint(equalTo: status.bottomAnchor, constant: AppSpacing.sm), timerLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor), flip.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.sm), flip.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md), grid.topAnchor.constraint(equalTo: flip.topAnchor), grid.trailingAnchor.constraint(equalTo: flip.leadingAnchor, constant: -AppSpacing.md), modeControl.centerXAnchor.constraint(equalTo: view.centerXAnchor), modeControl.bottomAnchor.constraint(equalTo: lensStack.topAnchor, constant: -AppSpacing.sm), lensStack.centerXAnchor.constraint(equalTo: view.centerXAnchor), lensStack.bottomAnchor.constraint(equalTo: recordButton.topAnchor, constant: -AppSpacing.lg), recordButton.centerXAnchor.constraint(equalTo: view.centerXAnchor), recordButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -AppSpacing.lg), recordButton.widthAnchor.constraint(equalToConstant: 72), recordButton.heightAnchor.constraint(equalToConstant: 72), info.centerXAnchor.constraint(equalTo: view.centerXAnchor), info.bottomAnchor.constraint(equalTo: recordButton.topAnchor, constant: -AppSpacing.md)])
        let tap = UITapGestureRecognizer(target: self, action: #selector(focus(_:))); view.addGestureRecognizer(tap); navigationItem.rightBarButtonItem = UIBarButtonItem(image: UIImage(systemName: "lock.shield.fill"), style: .plain, target: self, action: #selector(showProtection))
    }
    private func requestCamera() { AppLogger.step("Capture: requesting camera permission"); switch AVCaptureDevice.authorizationStatus(for: .video) { case .authorized: requestMicrophone(); case .notDetermined: AVCaptureDevice.requestAccess(for: .video) { [weak self] granted in DispatchQueue.main.async { granted ? self?.requestMicrophone() : self?.showPermission("Camera Access Needed", "TrueCut needs camera access to record protected videos.") } }; default: showPermission("Camera Access Needed", "TrueCut needs camera access to record protected videos.") } }
    private func requestMicrophone() { switch AVCaptureDevice.authorizationStatus(for: .audio) { case .authorized: configureSession(); case .notDetermined: AVCaptureDevice.requestAccess(for: .audio) { [weak self] granted in DispatchQueue.main.async { if granted { self?.configureSession() } else { self?.showPermission("Microphone Access Needed", "TrueCut needs microphone access to include audio in your recordings.") } } }; default: showPermission("Microphone Access Needed", "TrueCut needs microphone access to include audio in your recordings.") } }
    private func configureSession() { DispatchQueue.global(qos: .userInitiated).async { [weak self] in guard let self else { return }; AppLogger.step("Capture: configuring AVCaptureSession"); session.beginConfiguration(); session.sessionPreset = .high; defer { session.commitConfiguration(); session.startRunning(); DispatchQueue.main.async { self.preview.session = self.session; self.buildLensControls() } }; guard let camera = AVCaptureDevice.default(for: .video), let input = try? AVCaptureDeviceInput(device: camera), session.canAddInput(input), session.canAddOutput(movieOutput), session.canAddOutput(photoOutput) else { AppLogger.failure("Capture: camera unavailable"); return }; session.addInput(input); if let audio = AVCaptureDevice.default(for: .audio), let audioInput = try? AVCaptureDeviceInput(device: audio), session.canAddInput(audioInput) { session.addInput(audioInput) }; session.addOutput(movieOutput); session.addOutput(photoOutput); setOrientation() } }
    private func setOrientation() { if let connection = movieOutput.connection(with: .video), connection.isVideoOrientationSupported { connection.videoOrientation = .portrait } }
    private var currentCamera: AVCaptureDevice? { session.inputs.compactMap { ($0 as? AVCaptureDeviceInput)?.device }.first { $0.hasMediaType(.video) } }
    private func buildLensControls() { lensStack.arrangedSubviews.forEach { $0.removeFromSuperview() }; let devices = AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInUltraWideCamera, .builtInWideAngleCamera, .builtInTelephotoCamera], mediaType: .video, position: selectedPosition).devices; for (index, device) in devices.enumerated() { let title = device.deviceType == .builtInUltraWideCamera ? "0.5×" : device.deviceType == .builtInTelephotoCamera ? "2×" : "1×"; let b = UIButton(configuration: .plain()); b.setTitle(title, for: .normal); b.tintColor = .white; b.tag = index; b.addTarget(self, action: #selector(selectLens(_:)), for: .touchUpInside); b.accessibilityLabel = "Lens \(title)"; lensStack.addArrangedSubview(b) }; if currentCamera?.hasTorch == true { let torch = UIButton(type: .system); torch.setImage(UIImage(systemName: "flashlight.off.fill"), for: .normal); torch.tintColor = .white; torch.addTarget(self, action: #selector(toggleTorch), for: .touchUpInside); torch.accessibilityLabel = "Toggle torch"; lensStack.addArrangedSubview(torch) } }
    @objc private func selectLens(_ sender: UIButton) { let devices = AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInUltraWideCamera, .builtInWideAngleCamera, .builtInTelephotoCamera], mediaType: .video, position: selectedPosition).devices; guard sender.tag < devices.count, let input = try? AVCaptureDeviceInput(device: devices[sender.tag]) else { return }; session.beginConfiguration(); if let old = session.inputs.first(where: { ($0 as? AVCaptureDeviceInput)?.device.hasMediaType(.video) == true }) { session.removeInput(old) }; if session.canAddInput(input) { session.addInput(input) }; session.commitConfiguration(); AppLogger.step("Capture: lens selected \(sender.currentTitle ?? "unknown")") }
    @objc private func flipCamera() { selectedPosition = selectedPosition == .back ? .front : .back; let discovery = AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInWideAngleCamera], mediaType: .video, position: selectedPosition); guard let camera = discovery.devices.first, let input = try? AVCaptureDeviceInput(device: camera) else { return }; session.beginConfiguration(); session.inputs.filter { ($0 as? AVCaptureDeviceInput)?.device.hasMediaType(.video) == true }.forEach { session.removeInput($0) }; if session.canAddInput(input) { session.addInput(input) }; session.commitConfiguration(); buildLensControls(); AppLogger.step("Capture: camera switched") }
    @objc private func toggleTorch() { guard let camera = currentCamera, camera.hasTorch else { return }; try? camera.lockForConfiguration(); camera.torchMode = camera.torchMode == .on ? .off : .on; camera.unlockForConfiguration() }
    @objc private func toggleGrid() { gridView.isHidden.toggle() }
    @objc private func focus(_ gesture: UITapGestureRecognizer) { let point = gesture.location(in: view); guard let device = currentCamera, device.isFocusPointOfInterestSupported else { return }; let focus = preview.captureDevicePointConverted(fromLayerPoint: point); try? device.lockForConfiguration(); device.focusPointOfInterest = focus; device.focusMode = .autoFocus; if device.isExposurePointOfInterestSupported { device.exposurePointOfInterest = focus; device.exposureMode = .continuousAutoExposure }; device.unlockForConfiguration(); let indicator = UIView(frame: CGRect(x: point.x - 28, y: point.y - 28, width: 56, height: 56)); indicator.layer.borderColor = AppColors.accent.cgColor; indicator.layer.borderWidth = 2; view.addSubview(indicator); UIView.animate(withDuration: 0.25, animations: { indicator.alpha = 0.3 }, completion: { _ in indicator.removeFromSuperview() }) }
    @objc private func toggleRecording() { if modeControl.selectedSegmentIndex == 0 { guard !isFinalizing else { return }; capturePhoto(); return }; if movieOutput.isRecording { AppLogger.step("Capture: stopping recording"); movieOutput.stopRecording(); timer?.invalidate(); timer = nil; recordingStartedAt = nil; timerLabel.text = ""; isFinalizing = true; recordButton.isEnabled = false; recordButton.setImage(UIImage(systemName: "hourglass"), for: .normal); recordButton.tintColor = AppColors.warning; status.text = "●  FINALIZING ORIGINAL"; status.textColor = AppColors.warning; UIImpactFeedbackGenerator(style: .medium).impactOccurred() } else { guard !isFinalizing else { return }; guard session.isRunning else { showPermission("Camera Unavailable", "The camera is not currently available."); return }; let url = FileManager.default.temporaryDirectory.appendingPathComponent("capture-\(UUID().uuidString).mov"); AppLogger.step("Capture: starting local recording"); movieOutput.startRecording(to: url, recordingDelegate: self); recordingStartedAt = Date(); timerLabel.text = "00:00"; status.text = "●  RECORDING"; status.textColor = AppColors.danger; recordButton.setImage(UIImage(systemName: "stop.fill"), for: .normal); recordButton.tintColor = AppColors.danger; recordButton.accessibilityLabel = "Stop recording"; timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in guard let self, let started = self.recordingStartedAt else { return }; let seconds = Int(Date().timeIntervalSince(started)); self.timerLabel.text = String(format: "%02d:%02d", seconds / 60, seconds % 60) }; UIImpactFeedbackGenerator(style: .heavy).impactOccurred() } }
    @objc private func modeChanged() { let photo = modeControl.selectedSegmentIndex == 0; recordButton.accessibilityLabel = photo ? "Take protected photo" : "Record protected video"; timerLabel.text = ""; AppLogger.step("Capture: mode changed to \(photo ? "photo" : "video")") }
    private func capturePhoto() { guard session.isRunning else { return }; let settings = AVCapturePhotoSettings(format: [AVVideoCodecKey: AVVideoCodecType.jpeg]); AppLogger.step("Capture: taking local photo"); isFinalizing = true; recordButton.isEnabled = false; recordButton.setImage(UIImage(systemName: "hourglass"), for: .normal); recordButton.tintColor = AppColors.warning; status.text = "●  PROTECTING PHOTO"; status.textColor = AppColors.warning; photoOutput.capturePhoto(with: settings, delegate: self); UIImpactFeedbackGenerator(style: .medium).impactOccurred() }
    @objc private func showProtection() { let sheet = UIAlertController(title: "Capture Protection", message: "✓ Local integrity verification available\n✓ Hardware capability is reported by this device\n\nTrueCut proves file protection, not objective truth of what is depicted.", preferredStyle: .actionSheet); sheet.addAction(UIAlertAction(title: "Done", style: .cancel)); present(sheet, animated: true) }
    private func showPermission(_ title: String, _ message: String) { let alert = UIAlertController(title: title, message: message, preferredStyle: .alert); alert.addAction(UIAlertAction(title: "Cancel", style: .cancel)); alert.addAction(UIAlertAction(title: "Open Settings", style: .default) { _ in guard let url = URL(string: UIApplication.openSettingsURLString) else { return }; UIApplication.shared.open(url) }); present(alert, animated: true) }
    private func finalize(url: URL) { AppLogger.step("Protection: preparing recording"); status.text = "●  PROTECTING ORIGINAL"; status.textColor = AppColors.warning; Task { let digest = try? await environment.digestService.sha256(of: url); AppLogger.step("Protection: streaming digest complete"); let signing = try? await environment.signingService.prepareKey(); let fingerprint = try? await environment.signingService.publicKeyFingerprint(); AppLogger.step("Protection: evidence signing operation complete"); let evidence = digest.map { CaptureEvidence(captureID: UUID().uuidString, digest: $0, createdAt: Date(), locationDisclosure: locationDisclosure) }; var credentials: SealedAsset?; if let evidence { do { credentials = try await environment.credentialsService.seal(assetURL: url, evidence: evidence); AppLogger.step("Protection: C2PA sealed and re-validated") } catch { AppLogger.failure("Protection: C2PA sealing failed — \(error.localizedDescription)") } }; let protectedState: ProtectionStatus = (signing != nil && digest != nil && credentials != nil) ? .protected : .incomplete; let metadata = mediaMetadata(for: url); let finalURL = persistAsset(credentials?.url ?? url, captureID: evidence?.captureID ?? UUID().uuidString); let size = (try? FileManager.default.attributesOfItem(atPath: finalURL.path)[.size] as? NSNumber)?.int64Value ?? 0; let record = ProofRecord(id: UUID(), captureId: evidence?.captureID ?? UUID().uuidString, localAssetURL: finalURL, createdAt: Date(), duration: metadata.duration, width: metadata.width, height: metadata.height, frameRate: metadata.frameRate, locationDisclosure: locationDisclosure, protectionStatus: protectedState, provenanceStatus: credentials == nil ? .incomplete : .verifiedOriginal, publicKeyFingerprint: fingerprint, digestHex: digest?.sha256Hex, fileSize: size); if finalURL != url { try? FileManager.default.removeItem(at: url) }; do { try await environment.proofRepository.save(record); AppLogger.step("Protection: ProofRecord persisted (\(protectedState.rawValue))") } catch { AppLogger.failure("Protection: ProofRecord could not be saved: \(error.localizedDescription)") }; await MainActor.run { self.status.text = protectedState == .protected ? "●  PROTECTED ORIGINAL" : "●  PROTECTION INCOMPLETE"; self.status.textColor = protectedState == .protected ? AppColors.success : AppColors.warning; self.showResult(record) } } }
    private func mediaMetadata(for url: URL) -> (duration: TimeInterval, width: Int, height: Int, frameRate: Double) { let asset = AVAsset(url: url); let seconds = asset.duration.seconds.isFinite ? asset.duration.seconds : 0; guard let track = asset.tracks(withMediaType: .video).first else { return (seconds, 0, 0, 0) }; let size = track.naturalSize.applying(track.preferredTransform); return (seconds, Int(abs(size.width)), Int(abs(size.height)), Double(track.nominalFrameRate)) }
    private func persistAsset(_ source: URL, captureID: String) -> URL { let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent("TrueCut/Originals", isDirectory: true); try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true); let extensionName = source.pathExtension.isEmpty ? "mov" : source.pathExtension; let destination = directory.appendingPathComponent("\(captureID).\(extensionName)"); try? FileManager.default.removeItem(at: destination); do { try FileManager.default.moveItem(at: source, to: destination) } catch { do { try FileManager.default.copyItem(at: source, to: destination) } catch { AppLogger.failure("Storage: could not move or copy captured media: \(error.localizedDescription)"); return source } }; guard FileManager.default.fileExists(atPath: destination.path) else { AppLogger.failure("Storage: captured media destination does not exist after save"); return source }; try? FileManager.default.setAttributes([.protectionKey: FileProtectionType.completeUnlessOpen], ofItemAtPath: destination.path); AppLogger.step("Storage: local original saved at \(destination.lastPathComponent)"); return destination }
    private func resetCaptureUI() { isFinalizing = false; recordButton.isEnabled = true; recordButton.setImage(UIImage(systemName: modeControl.selectedSegmentIndex == 0 ? "camera.fill" : "circle.fill"), for: .normal); recordButton.tintColor = .systemRed; recordButton.accessibilityLabel = modeControl.selectedSegmentIndex == 0 ? "Take protected photo" : "Record protected video"; timerLabel.text = ""; recordingStartedAt = nil }
    private func showResult(_ record: ProofRecord) { resetCaptureUI(); let message = record.protectionStatus == .protected ? "Integrity evidence and C2PA Content Credentials were validated locally." : "Your recording was saved, but complete protection could not be finished. It is not marked as verified."; let alert = UIAlertController(title: record.protectionStatus.title, message: message, preferredStyle: .alert); alert.addAction(UIAlertAction(title: "Done", style: .default)); present(alert, animated: true) }
}
extension CameraViewController: AVCaptureFileOutputRecordingDelegate { func fileOutput(_ output: AVCaptureFileOutput, didFinishRecordingTo outputFileURL: URL, from connections: [AVCaptureConnection], error: Error?) { DispatchQueue.main.async { if let error { AppLogger.failure("Capture: recording failed \(error.localizedDescription)"); self.resetCaptureUI(); self.status.text = "●  RECORDING FAILED"; self.status.textColor = AppColors.danger } else { self.finalize(url: outputFileURL) } } } }
extension CameraViewController: AVCapturePhotoCaptureDelegate { func photoOutput(_ output: AVCapturePhotoOutput, didFinishProcessingPhoto photo: AVCapturePhoto, error: Error?) { guard error == nil, let data = photo.fileDataRepresentation() else { AppLogger.failure("Capture: photo processing failed"); resetCaptureUI(); status.text = "●  PHOTO FAILED"; status.textColor = AppColors.danger; return }; let url = FileManager.default.temporaryDirectory.appendingPathComponent("photo-\(UUID().uuidString).jpg"); do { try data.write(to: url, options: .atomic); AppLogger.step("Capture: photo saved locally, entering protection flow"); finalize(url: url) } catch { AppLogger.failure("Capture: could not save photo"); resetCaptureUI(); status.text = "●  PHOTO FAILED"; status.textColor = AppColors.danger } } }
final class GridOverlayView: UIView { override func draw(_ rect: CGRect) { UIColor.white.withAlphaComponent(0.3).setStroke(); let path = UIBezierPath(); for fraction in [1.0 / 3.0, 2.0 / 3.0] { path.move(to: CGPoint(x: rect.width * fraction, y: 0)); path.addLine(to: CGPoint(x: rect.width * fraction, y: rect.height)); path.move(to: CGPoint(x: 0, y: rect.height * fraction)); path.addLine(to: CGPoint(x: rect.width, y: rect.height * fraction)) }; path.lineWidth = 1; path.stroke() } }

final class ProofVaultViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegate, UISearchResultsUpdating {
    private let environment: AppEnvironment; private var records = [ProofRecord](); private var filtered = [ProofRecord](); private var collection: UICollectionView!; private let filter = UISegmentedControl(items: ["All", "Protected", "Attention"]); private var longPressInstalled = false
    init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() { super.viewDidLoad(); title = "Proof Vault"; view.backgroundColor = AppColors.background; let layout = UICollectionViewFlowLayout(); layout.minimumInteritemSpacing = AppSpacing.sm; layout.minimumLineSpacing = AppSpacing.md; collection = UICollectionView(frame: .zero, collectionViewLayout: layout); collection.register(ProofCell.self, forCellWithReuseIdentifier: "cell"); collection.backgroundColor = .clear; collection.dataSource = self; collection.delegate = self; collection.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(collection); filter.selectedSegmentIndex = 0; filter.addTarget(self, action: #selector(applyFilter), for: .valueChanged); filter.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(filter); let search = UISearchController(searchResultsController: nil); search.searchResultsUpdater = self; navigationItem.searchController = search; NSLayoutConstraint.activate([filter.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.sm), filter.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), filter.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md), collection.topAnchor.constraint(equalTo: filter.bottomAnchor, constant: AppSpacing.sm), collection.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), collection.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md), collection.bottomAnchor.constraint(equalTo: view.bottomAnchor)]); load() }
    override func viewDidAppear(_ animated: Bool) { super.viewDidAppear(animated); load(); if !longPressInstalled { collection.addGestureRecognizer(UILongPressGestureRecognizer(target: self, action: #selector(handleLongPress(_:)))); longPressInstalled = true }; guard UserDefaults.standard.bool(forKey: "requireFaceID") else { return }; let context = LAContext(); context.evaluatePolicy(.deviceOwnerAuthentication, localizedReason: "Unlock your local Proof Vault.") { [weak self] success, _ in if !success { DispatchQueue.main.async { self?.tabBarController?.selectedIndex = 0 } } } }
    private func load() { AppLogger.step("Vault: loading local ProofRecords"); Task { let loaded = (try? await environment.proofRepository.load()) ?? []; await MainActor.run { self.records = loaded; self.filtered = loaded; self.collection.reloadData(); AppLogger.step("Vault: loaded \(loaded.count) local ProofRecords") } } }
    @objc private func handleLongPress(_ gesture: UILongPressGestureRecognizer) { guard gesture.state == .began else { return }; let point = gesture.location(in: collection); guard let indexPath = collection.indexPathForItem(at: point), indexPath.item < filtered.count else { return }; let record = filtered[indexPath.item]; let sheet = UIAlertController(title: "Video Options", message: "Choose an action for this local original.", preferredStyle: .actionSheet); sheet.addAction(UIAlertAction(title: "Delete Permanently", style: .destructive) { [weak self] _ in self?.confirmDelete(record) }); sheet.addAction(UIAlertAction(title: "Cancel", style: .cancel)); present(sheet, animated: true) }
    private func confirmDelete(_ record: ProofRecord) { let alert = UIAlertController(title: "Delete Original Permanently?", message: "TrueCut does not keep a server copy. This will permanently remove the local video and its Proof Vault record.", preferredStyle: .alert); alert.addAction(UIAlertAction(title: "Cancel", style: .cancel)); alert.addAction(UIAlertAction(title: "Delete Permanently", style: .destructive) { [weak self] _ in self?.delete(record) }); present(alert, animated: true) }
    private func delete(_ record: ProofRecord) { AppLogger.step("Vault: permanently deleting local original"); Task { try? FileManager.default.removeItem(at: record.localAssetURL); try? await environment.proofRepository.delete(record); await MainActor.run { self.records.removeAll { $0.id == record.id }; self.filtered.removeAll { $0.id == record.id }; self.collection.reloadData() } } }
    @objc private func applyFilter() { filtered = filter.selectedSegmentIndex == 1 ? records.filter { $0.protectionStatus == .protected } : filter.selectedSegmentIndex == 2 ? records.filter { $0.protectionStatus != .protected } : records; collection.reloadData() }
    func updateSearchResults(for searchController: UISearchController) { let query = searchController.searchBar.text ?? ""; filtered = query.isEmpty ? records : records.filter { $0.captureId.localizedCaseInsensitiveContains(query) }; applyFilter() }
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int { filtered.count }
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell { let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! ProofCell; cell.configure(record: filtered[indexPath.item]); return cell }
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) { navigationController?.pushViewController(ProofDetailViewController(record: filtered[indexPath.item], environment: environment), animated: true) }
}
extension ProofVaultViewController: UICollectionViewDelegateFlowLayout { func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize { let width = (collectionView.bounds.width - AppSpacing.sm) / 2; return CGSize(width: width, height: width * 0.9) } }
final class ProofCell: UICollectionViewCell { private let imageView = UIImageView(); private let label = UIBuilder.label("", style: AppTypography.caption); override init(frame: CGRect) { super.init(frame: frame); contentView.backgroundColor = AppColors.surface; contentView.layer.cornerRadius = AppRadius.card; contentView.clipsToBounds = true; imageView.contentMode = .scaleAspectFill; imageView.backgroundColor = .secondarySystemFill; imageView.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview(imageView); label.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview(label); NSLayoutConstraint.activate([imageView.topAnchor.constraint(equalTo: contentView.topAnchor), imageView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor), imageView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor), imageView.heightAnchor.constraint(equalTo: imageView.widthAnchor, multiplier: 0.68), label.topAnchor.constraint(equalTo: imageView.bottomAnchor, constant: AppSpacing.xs), label.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: AppSpacing.sm), label.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -AppSpacing.xs), label.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -AppSpacing.xs)]) }; required init?(coder: NSCoder) { fatalError() }; func configure(record: ProofRecord) { imageView.image = UIImage(systemName: ["jpg", "jpeg", "png", "heic"].contains(record.localAssetURL.pathExtension.lowercased()) ? "photo" : "video.fill"); imageView.tintColor = AppColors.secondaryText; label.text = "\(record.protectionStatus == .protected ? "✓ Protected" : "⚠ Attention")\n\(record.createdAt.formatted(date: .abbreviated, time: .shortened))"; label.textColor = record.protectionStatus == .protected ? AppColors.success : AppColors.warning; let photoExtensions = ["jpg", "jpeg", "png", "heic"]; if photoExtensions.contains(record.localAssetURL.pathExtension.lowercased()) { imageView.image = UIImage(contentsOfFile: record.localAssetURL.path) ?? UIImage(systemName: "photo"); return }; guard FileManager.default.fileExists(atPath: record.localAssetURL.path) else { return }; Task { let generator = AVAssetImageGenerator(asset: AVAsset(url: record.localAssetURL)); generator.appliesPreferredTrackTransform = true; if let cg = try? await generator.image(at: .zero).image { await MainActor.run { self.imageView.image = UIImage(cgImage: cg) } } } } }
