import UIKit
import AVKit
import UniformTypeIdentifiers
import LocalAuthentication

final class ProofDetailViewController: UIViewController {
    private let record: ProofRecord
    private let environment: AppEnvironment
    init(record: ProofRecord, environment: AppEnvironment) { self.record = record; self.environment = environment; super.init(nibName: nil, bundle: nil) }
    required init?(coder: NSCoder) { fatalError("Programmatic controller") }
    override func viewDidLoad() {
        super.viewDidLoad(); title = "Proof Detail"; view.backgroundColor = AppColors.background
        let stack = UIStackView(); stack.axis = .vertical; stack.spacing = AppSpacing.md; stack.translatesAutoresizingMaskIntoConstraints = false
        let scroll = UIScrollView(); scroll.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(scroll); scroll.addSubview(stack)
        NSLayoutConstraint.activate([scroll.topAnchor.constraint(equalTo: view.topAnchor), scroll.bottomAnchor.constraint(equalTo: view.bottomAnchor), scroll.leadingAnchor.constraint(equalTo: view.leadingAnchor), scroll.trailingAnchor.constraint(equalTo: view.trailingAnchor), stack.topAnchor.constraint(equalTo: scroll.contentLayoutGuide.topAnchor, constant: AppSpacing.md), stack.leadingAnchor.constraint(equalTo: scroll.frameLayoutGuide.leadingAnchor, constant: AppSpacing.md), stack.trailingAnchor.constraint(equalTo: scroll.frameLayoutGuide.trailingAnchor, constant: -AppSpacing.md), stack.bottomAnchor.constraint(equalTo: scroll.contentLayoutGuide.bottomAnchor, constant: -AppSpacing.lg)])
        let imageExtensions = ["jpg", "jpeg", "png", "heic"]
        if imageExtensions.contains(record.localAssetURL.pathExtension.lowercased()), let image = UIImage(contentsOfFile: record.localAssetURL.path) { let imageView = UIImageView(image: image); imageView.contentMode = .scaleAspectFit; imageView.backgroundColor = .black; imageView.heightAnchor.constraint(equalToConstant: 230).isActive = true; imageView.accessibilityLabel = "Captured photo"; stack.addArrangedSubview(imageView) } else if FileManager.default.fileExists(atPath: record.localAssetURL.path) { let player = AVPlayerViewController(); player.player = AVPlayer(url: record.localAssetURL); player.view.heightAnchor.constraint(equalToConstant: 230).isActive = true; addChild(player); stack.addArrangedSubview(player.view); player.didMove(toParent: self); player.player?.play() } else { stack.addArrangedSubview(UIBuilder.label("This local original is unavailable.", style: AppTypography.body, color: AppColors.warning)) }
        stack.addArrangedSubview(UIBuilder.label(record.protectionStatus.title, style: AppTypography.title, color: record.protectionStatus == .protected ? AppColors.success : AppColors.warning))
        stack.addArrangedSubview(UIBuilder.label("\(record.protectionStatus == .protected ? "✓ File integrity" : "○ File integrity incomplete")\n\(record.provenanceStatus == .verifiedOriginal ? "✓ Content Credentials" : "○ Content Credentials unavailable")", style: AppTypography.body))
        let share = UIBuilder.button("Share Protected Original", image: UIImage(systemName: "square.and.arrow.up")); share.addTarget(self, action: #selector(shareAsset), for: .touchUpInside); stack.addArrangedSubview(share)
        let technical = UIBuilder.button("View Technical Proof", image: UIImage(systemName: "doc.text.magnifyingglass"), primary: false); technical.addTarget(self, action: #selector(showTechnical), for: .touchUpInside); stack.addArrangedSubview(technical)
        stack.addArrangedSubview(UIBuilder.label("CAPTURE\nDate     \(record.createdAt.formatted(date: .abbreviated, time: .shortened))\nDuration     \(record.duration > 0 ? String(format: "%.0fs", record.duration) : "Not available")\nResolution     \(record.width > 0 ? "\(record.width) × \(record.height)" : "Not available")\nFrame rate     \(record.frameRate > 0 ? String(format: "%.1f FPS", record.frameRate) : "Not available")\n\nLOCATION\n\(record.locationDisclosure.title)", style: AppTypography.body))
    }
    @objc private func shareAsset() { guard FileManager.default.fileExists(atPath: record.localAssetURL.path) else { return }; present(UIActivityViewController(activityItems: [record.localAssetURL], applicationActivities: nil), animated: true) }
    @objc private func showTechnical() { navigationController?.pushViewController(TechnicalProofViewController(record: record, environment: environment), animated: true) }
}

final class TechnicalProofViewController: UIViewController {
    private let record: ProofRecord
    init(record: ProofRecord, environment: AppEnvironment) { self.record = record; super.init(nibName: nil, bundle: nil) }
    required init?(coder: NSCoder) { fatalError("Programmatic controller") }
    override func viewDidLoad() { super.viewDidLoad(); title = "Technical Proof"; view.backgroundColor = AppColors.background; let label = UIBuilder.label("CAPTURE ID\n\(record.captureId)\n\nLOCAL DIGEST\n\(record.digestHex ?? "Not available")\n\nPUBLIC KEY FINGERPRINT\n\(record.publicKeyFingerprint ?? "Not available")\n\nC2PA STATUS\n\(record.provenanceStatus == .verifiedOriginal ? "Validated locally" : "Not available")\n\nLOCATION\n\(record.locationDisclosure.title)", style: AppTypography.mono); label.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(label); NSLayoutConstraint.activate([label.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.md), label.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), label.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md)]) }
}

final class CompareViewController: UIViewController, UIDocumentPickerDelegate {
    private let original: URL; private let environment: AppEnvironment; private let result = UIBuilder.label("Select another MP4 or MOV to compare locally.", style: AppTypography.body)
    init(original: URL, environment: AppEnvironment) { self.original = original; self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError("Programmatic controller") }
    override func viewDidLoad() { super.viewDidLoad(); title = "Compare"; view.backgroundColor = AppColors.background; let button = UIBuilder.button("Choose Candidate Video", image: AppIcons.folder); button.addTarget(self, action: #selector(pick), for: .touchUpInside); result.translatesAutoresizingMaskIntoConstraints = false; button.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(result); view.addSubview(button); NSLayoutConstraint.activate([result.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.lg), result.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), result.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md), button.topAnchor.constraint(equalTo: result.bottomAnchor, constant: AppSpacing.md), button.centerXAnchor.constraint(equalTo: view.centerXAnchor)]) }
    @objc private func pick() { let picker = UIDocumentPickerViewController(forOpeningContentTypes: [UTType.movie]); picker.delegate = self; present(picker, animated: true) }
    func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL]) { guard let candidate = urls.first else { return }; result.text = "Comparing locally…"; Task { let comparison = try? await environment.comparisonService.compare(original: original, candidate: candidate); await MainActor.run { self.result.text = comparison?.identical == true ? "FILES IDENTICAL\n\nThe candidate matches the protected original digest." : "FILES DIFFER\n\nThe selected file is not identical to this protected TrueCut original." } } }
}

final class InspectorViewController: UIViewController, UIDocumentPickerDelegate {
    private let environment: AppEnvironment; private let result = UIBuilder.label("Inspect a Video\n\nCheck supported provenance and integrity information for a video you've received.", style: AppTypography.title)
    init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError("Programmatic controller") }
    override func viewDidLoad() { super.viewDidLoad(); title = "Inspect"; view.backgroundColor = AppColors.background; result.textAlignment = .center; let button = UIBuilder.button("Choose Video", image: AppIcons.folder); button.addTarget(self, action: #selector(pick), for: .touchUpInside); result.translatesAutoresizingMaskIntoConstraints = false; button.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(result); view.addSubview(button); NSLayoutConstraint.activate([result.centerXAnchor.constraint(equalTo: view.centerXAnchor), result.centerYAnchor.constraint(equalTo: view.centerYAnchor, constant: -40), result.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.lg), result.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.lg), button.topAnchor.constraint(equalTo: result.bottomAnchor, constant: AppSpacing.lg), button.centerXAnchor.constraint(equalTo: view.centerXAnchor)]) }
    @objc private func pick() { let picker = UIDocumentPickerViewController(forOpeningContentTypes: [UTType.movie]); picker.delegate = self; present(picker, animated: true) }
    func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL]) { guard let url = urls.first else { return }; result.text = "ANALYZING\n\nReading file\nChecking Content Credentials\nValidating provenance"; Task { let provenance = try? await environment.credentialsService.verify(assetURL: url); await MainActor.run { self.result.text = provenance?.message ?? "Unable to inspect this file."; self.result.font = AppTypography.body } } }
}

final class SettingsViewController: UIViewController {
    private let environment: AppEnvironment
    init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError("Programmatic controller") }
    override func viewDidLoad() { super.viewDidLoad(); title = "Settings"; view.backgroundColor = AppColors.background; let label = UIBuilder.label("TrueCut Settings\n\nCAMERA\nResolution     High\nFrame Rate     Auto\nGrid           Off\nAudio Recording     On\n\nPRIVACY\nLocation disclosure     Off\n\nPROTECTION\nHardware protection status     Device-reported\nContent Credentials     Local C2PA\n\nSTORAGE\nOriginal media remains on this device.\nTrueCut does not upload your original videos or photos in this version.\n\nABOUT\nHow TrueCut Works\nPrivacy\nTerms\nApp Version 1.0", style: AppTypography.body); label.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(label); NSLayoutConstraint.activate([label.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.md), label.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), label.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md)]) }
}
