import UIKit
import UniformTypeIdentifiers

final class ProofDetailViewController: UIViewController {
    let record: ProofRecord; let environment: AppEnvironment; let stack = UIStackView()
    init(record: ProofRecord, environment: AppEnvironment) { self.record = record; self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() { super.viewDidLoad(); title = "Proof Detail"; view.backgroundColor = AppColors.background; stack.axis = .vertical; stack.spacing = AppSpacing.md; stack.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(stack); NSLayoutConstraint.activate([stack.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: AppSpacing.md), stack.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.md), stack.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.md)]); let title = UIBuilder.label(record.protectionStatus.title, style: AppTypography.title); let detail = UIBuilder.label("\(record.protectionStatus == .protected ? "✓ Integrity evidence" : "○ Content Credentials unavailable")\n\(record.digestHex == nil ? "○ Digest unavailable" : "✓ Local SHA-256 digest")\n○ Network timestamp unavailable in Phase 1\n\nCapture ID  \(record.captureId)", style: AppTypography.body); stack.addArrangedSubview(title); stack.addArrangedSubview(detail); let share = UIBuilder.button("Share Protected Original", image: UIImage(systemName: "square.and.arrow.up")); share.addTarget(self, action: #selector(shareFile), for: .touchUpInside); stack.addArrangedSubview(share); Task { let provenance = try? await environment.credentialsService.verify(assetURL: record.localAssetURL); await MainActor.run { let technical = UIBuilder.label("\nTechnical Proof\nClaim Generator: \(provenance?.claimGenerator ?? "Not available")\nManifest Identifier: \(provenance?.manifestIdentifier ?? "Not available")\nAsset Binding: \(provenance?.assetBindingValid == true ? "Valid" : "Not available")\nDigital Source Type: \(provenance?.digitalSourceType ?? "Not available")", style: AppTypography.mono); self.stack.addArrangedSubview(technical) } } }
    @objc private func shareFile() { guard FileManager.default.fileExists(atPath: record.localAssetURL.path) else { return }; present(UIActivityViewController(activityItems: [record.localAssetURL], applicationActivities: nil), animated: true) }
}

final class InspectorViewController: UIViewController, UIDocumentPickerDelegate {
    let environment: AppEnvironment; let choose = UIBuilder.button("Choose Video", image: AppIcons.folder); let result = UIBuilder.label("Inspect a Video\n\nCheck supported provenance and integrity information for a video you've received.", style: AppTypography.title); init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() { super.viewDidLoad(); title = "Inspect"; view.backgroundColor = AppColors.background; result.textAlignment = .center; choose.addTarget(self, action: #selector(pick), for: .touchUpInside); result.translatesAutoresizingMaskIntoConstraints = false; choose.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(result); view.addSubview(choose); NSLayoutConstraint.activate([result.centerXAnchor.constraint(equalTo: view.centerXAnchor), result.centerYAnchor.constraint(equalTo: view.centerYAnchor, constant: -40), result.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: AppSpacing.lg), result.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -AppSpacing.lg), choose.topAnchor.constraint(equalTo: result.bottomAnchor, constant: AppSpacing.lg), choose.centerXAnchor.constraint(equalTo: view.centerXAnchor)]) }
    @objc private func pick() { let picker = UIDocumentPickerViewController(forOpeningContentTypes: [UTType.movie]); picker.delegate = self; present(picker, animated: true) }
    func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL]) { guard let url = urls.first else { return }; Task { let r = try? await environment.credentialsService.verify(assetURL: url); await MainActor.run { self.result.text = r?.message ?? "Unable to inspect this file."; self.result.font = AppTypography.body } } }
}

final class SettingsViewController: UIViewController {
    let environment: AppEnvironment; init(environment: AppEnvironment) { self.environment = environment; super.init(nibName: nil, bundle: nil) }; required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() { super.viewDidLoad(); title = "Settings"; view.backgroundColor = AppColors.background; let scroll = UIScrollView(); let stack = UIStackView(); stack.axis = .vertical; stack.spacing = AppSpacing.sm; stack.translatesAutoresizingMaskIntoConstraints = false; scroll.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(scroll); scroll.addSubview(stack); NSLayoutConstraint.activate([scroll.topAnchor.constraint(equalTo: view.topAnchor), scroll.bottomAnchor.constraint(equalTo: view.bottomAnchor), scroll.leadingAnchor.constraint(equalTo: view.leadingAnchor), scroll.trailingAnchor.constraint(equalTo: view.trailingAnchor), stack.topAnchor.constraint(equalTo: scroll.contentLayoutGuide.topAnchor, constant: AppSpacing.md), stack.leadingAnchor.constraint(equalTo: scroll.frameLayoutGuide.leadingAnchor, constant: AppSpacing.md), stack.trailingAnchor.constraint(equalTo: scroll.frameLayoutGuide.trailingAnchor, constant: -AppSpacing.md), stack.bottomAnchor.constraint(equalTo: scroll.contentLayoutGuide.bottomAnchor, constant: -AppSpacing.lg)]); let heading = UIBuilder.label("TrueCut Settings", style: AppTypography.title); stack.addArrangedSubview(heading); addSection("CAMERA", ["Resolution     High", "Frame Rate     Auto", "Grid           Off", "Audio Recording On"], to: stack); addSection("PRIVACY", ["Location       Off", "Face ID for Proof Vault  Off"], to: stack); addSection("PROTECTION", ["Hardware Protection Status     Checking on device", "Content Credentials Status       Not available yet", "Public Key Fingerprint             Created locally when capture protection runs"], to: stack); addSection("STORAGE", ["TrueCut Storage Used             Local only", "Manage Local Originals"], to: stack); addSection("ABOUT", ["TrueCut does not upload your original videos in this version.", "How TrueCut Works", "Privacy", "Terms", "App Version 1.0"], to: stack) }
    private func addSection(_ title: String, _ rows: [String], to stack: UIStackView) { let label = UIBuilder.label(title, style: AppTypography.caption, color: AppColors.secondaryText); stack.addArrangedSubview(label); for row in rows { let l = UIBuilder.label(row, style: AppTypography.body); l.backgroundColor = AppColors.surface; l.layer.cornerRadius = AppRadius.button; l.layer.masksToBounds = true; l.isAccessibilityElement = true; l.accessibilityLabel = row; stack.addArrangedSubview(l); l.heightAnchor.constraint(greaterThanOrEqualToConstant: 48).isActive = true } }
}
